import { createRng, type Rng } from "../../seed/rng";
import { BASS_RIFFS } from "./types";
import type {
  BassHit,
  MusicArrangementProfile,
  MusicBassRiffFamily,
  MusicCue,
  MusicDrumProfile,
  MusicGroove,
  MusicDrumKit,
  MusicPulseRole,
  MusicScaleName,
  MusicStyleName,
  MusicStyleProfile,
  MusicVoiceEngine,
  MusicVoiceType,
} from "./types";
import {
  applyMissionTints,
  arrangementAffinityScore,
  assignmentRng,
  campaignMusicContexts,
  musicMissionContext,
  pickAssignedItem,
  pickBestByScore,
  styleAffinityScore,
} from "./missionContext";

type Range = readonly [number, number];

type StyleBlueprint = {
  name: MusicStyleName;
  scales: readonly MusicScaleName[];
  grooves: readonly MusicGroove[];
  grooveVariants: readonly (0 | 1 | 2)[];
  progressionVariants: readonly (0 | 1 | 2 | 3)[];
  bassRiffFamily: MusicBassRiffFamily;
  tempoBias: Range;
  swing: Range;
  bassTypes: readonly MusicVoiceType[];
  pulseTypes: readonly MusicVoiceType[];
  melodyTypes: readonly MusicVoiceType[];
  counterTypes: readonly MusicVoiceType[];
  padTypes: readonly MusicVoiceType[];
  padDetunes: readonly (readonly [number, number, number, number])[];
  padLfoRate: Range;
  padLfoDepth: Range;
  padQ: Range;
  delayBeats: readonly number[];
  delayFeedback: Range;
  delayWet: Range;
  reverbSeconds: Range;
  reverbDecay: Range;
  reverbSend: Range;
  reverbWet: Range;
  cutoff: Range;
  bassStrides: readonly (2 | 4 | 8)[];
  pulseStrides: readonly (1 | 2 | 4)[];
  melodyOctaves: readonly (1 | 2)[];
  rhythmShifts: readonly (0 | 1 | 2)[];
  counterChance: Range;
  drumDensity: Range;
  voiceEngine: MusicVoiceEngine;
  drumKit: MusicDrumKit;
  pulseRole: MusicPulseRole;
  saturation: Range;
  drum: MusicDrumProfile;
};

const STYLE_BLUEPRINTS: readonly StyleBlueprint[] = [
  {
    name: "neon-arpeggio",
    scales: ["major", "mixolydian", "dorian"],
    grooves: ["pulse", "shuffle"],
    grooveVariants: [0, 1],
    progressionVariants: [0, 1],
    bassRiffFamily: "classic",
    tempoBias: [-1, 3],
    swing: [0.008, 0.026],
    bassTypes: ["sawtooth", "square"],
    pulseTypes: ["square", "sawtooth"],
    melodyTypes: ["sawtooth", "square"],
    counterTypes: ["triangle", "sine"],
    padTypes: ["sawtooth", "square"],
    padDetunes: [[-7, -15, 11, 5], [-4, -11, 8, 3]],
    padLfoRate: [0.42, 0.66],
    padLfoDepth: [120, 210],
    padQ: [0.7, 1.1],
    delayBeats: [0.5, 0.75, 1],
    delayFeedback: [0.22, 0.34],
    delayWet: [0.2, 0.32],
    reverbSeconds: [0.8, 1.25],
    reverbDecay: [2.1, 2.8],
    reverbSend: [0.16, 0.24],
    reverbWet: [0.16, 0.25],
    cutoff: [720, 1220],
    bassStrides: [2],
    pulseStrides: [1, 2],
    melodyOctaves: [2],
    rhythmShifts: [0, 1],
    counterChance: [0.52, 0.8],
    drumDensity: [0.92, 1],
    voiceEngine: "pwm",
    drumKit: "gated",
    pulseRole: "arp",
    saturation: [0.14, 0.22],
    drum: {
      kickStart: 188, kickEnd: 42, kickTail: 0.16,
      snareBody: 210, snareNoise: 1900, hatFrequency: 7200, openHatFrequency: 3300,
      tomStart: 180, tomEnd: 110, impactStart: 108, impactEnd: 31, noisePan: -0.08,
    },
  },
  {
    name: "industrial-march",
    scales: ["natural minor", "dorian", "phrygian"],
    grooves: ["march"],
    grooveVariants: [0, 2],
    progressionVariants: [1, 3],
    bassRiffFamily: "industrial",
    tempoBias: [0, 3],
    swing: [0.002, 0.014],
    bassTypes: ["square", "sawtooth"],
    pulseTypes: ["square", "triangle"],
    melodyTypes: ["sawtooth", "triangle"],
    counterTypes: ["triangle", "square"],
    padTypes: ["sawtooth", "triangle"],
    padDetunes: [[-9, -17, 14, 6], [-6, -13, 10, 4]],
    padLfoRate: [0.28, 0.48],
    padLfoDepth: [90, 160],
    padQ: [0.9, 1.4],
    delayBeats: [0.5, 0.75],
    delayFeedback: [0.16, 0.27],
    delayWet: [0.14, 0.23],
    reverbSeconds: [0.65, 1.05],
    reverbDecay: [2.6, 3.3],
    reverbSend: [0.12, 0.2],
    reverbWet: [0.13, 0.21],
    cutoff: [500, 900],
    bassStrides: [2, 4],
    pulseStrides: [2, 4],
    melodyOctaves: [1, 2],
    rhythmShifts: [0, 2],
    counterChance: [0.32, 0.58],
    drumDensity: [0.9, 1],
    voiceEngine: "dual-osc",
    drumKit: "industrial",
    pulseRole: "stab",
    saturation: [0.28, 0.4],
    drum: {
      kickStart: 204, kickEnd: 36, kickTail: 0.2,
      snareBody: 176, snareNoise: 1600, hatFrequency: 6100, openHatFrequency: 2800,
      tomStart: 160, tomEnd: 92, impactStart: 122, impactEnd: 27, noisePan: 0.02,
    },
  },
  {
    name: "acid-grid",
    scales: ["natural minor", "mixolydian", "dorian"],
    grooves: ["pulse", "shuffle"],
    grooveVariants: [1, 2],
    progressionVariants: [2, 3],
    bassRiffFamily: "syncopated",
    tempoBias: [1, 5],
    swing: [0.018, 0.04],
    bassTypes: ["sawtooth", "square"],
    pulseTypes: ["sawtooth", "square"],
    melodyTypes: ["square", "sawtooth"],
    counterTypes: ["square", "triangle"],
    padTypes: ["square", "sawtooth"],
    padDetunes: [[-12, -21, 17, 8], [-8, -18, 13, 6]],
    padLfoRate: [0.62, 0.95],
    padLfoDepth: [160, 280],
    padQ: [1.1, 1.8],
    delayBeats: [0.375, 0.5, 0.75],
    delayFeedback: [0.28, 0.42],
    delayWet: [0.24, 0.38],
    reverbSeconds: [0.55, 0.95],
    reverbDecay: [1.7, 2.4],
    reverbSend: [0.13, 0.22],
    reverbWet: [0.14, 0.23],
    cutoff: [850, 1450],
    bassStrides: [2],
    pulseStrides: [1],
    melodyOctaves: [2],
    rhythmShifts: [1, 2],
    counterChance: [0.44, 0.7],
    drumDensity: [0.94, 1],
    voiceEngine: "acid-res",
    drumKit: "analog-808",
    pulseRole: "arp",
    saturation: [0.2, 0.32],
    drum: {
      kickStart: 220, kickEnd: 48, kickTail: 0.13,
      snareBody: 236, snareNoise: 2350, hatFrequency: 8200, openHatFrequency: 3900,
      tomStart: 196, tomEnd: 124, impactStart: 94, impactEnd: 34, noisePan: -0.14,
    },
  },
  {
    name: "orbital-drift",
    scales: ["dorian", "major", "mixolydian"],
    grooves: ["pulse", "march"],
    grooveVariants: [0, 1],
    progressionVariants: [0, 2],
    bassRiffFamily: "sparse",
    tempoBias: [-2, 2],
    swing: [0.012, 0.032],
    bassTypes: ["triangle", "sawtooth"],
    pulseTypes: ["triangle", "square"],
    melodyTypes: ["triangle", "sawtooth"],
    counterTypes: ["triangle", "square"],
    padTypes: ["triangle", "sawtooth"],
    padDetunes: [[-3, -8, 7, 2], [-2, -6, 5, 1]],
    padLfoRate: [0.18, 0.36],
    padLfoDepth: [70, 145],
    padQ: [0.45, 0.85],
    delayBeats: [0.75, 1, 1.5],
    delayFeedback: [0.28, 0.42],
    delayWet: [0.22, 0.34],
    reverbSeconds: [1.05, 1.5],
    reverbDecay: [2.4, 3.4],
    reverbSend: [0.18, 0.28],
    reverbWet: [0.18, 0.28],
    cutoff: [560, 980],
    bassStrides: [2, 4],
    pulseStrides: [1, 2],
    melodyOctaves: [1, 2],
    rhythmShifts: [0, 1],
    counterChance: [0.62, 0.9],
    drumDensity: [0.7, 0.9],
    voiceEngine: "dual-osc",
    drumKit: "gated",
    pulseRole: "arp",
    saturation: [0.1, 0.18],
    drum: {
      kickStart: 150, kickEnd: 52, kickTail: 0.25,
      snareBody: 188, snareNoise: 1300, hatFrequency: 5100, openHatFrequency: 2400,
      tomStart: 142, tomEnd: 86, impactStart: 82, impactEnd: 24, noisePan: 0.16,
    },
  },
  {
    name: "cinematic-tension",
    scales: ["natural minor", "dorian", "phrygian"],
    grooves: ["march"],
    grooveVariants: [0, 1],
    progressionVariants: [1, 2],
    bassRiffFamily: "descending",
    tempoBias: [-2, 2],
    swing: [0, 0.012],
    bassTypes: ["triangle", "sawtooth"],
    pulseTypes: ["square", "sawtooth"],
    melodyTypes: ["sawtooth", "triangle"],
    counterTypes: ["triangle", "square"],
    padTypes: ["triangle", "sawtooth"],
    padDetunes: [[-5, -10, 9, 3], [-7, -12, 11, 4]],
    padLfoRate: [0.22, 0.42],
    padLfoDepth: [100, 200],
    padQ: [0.7, 1.25],
    delayBeats: [0.5, 0.75, 1],
    delayFeedback: [0.2, 0.34],
    delayWet: [0.16, 0.28],
    reverbSeconds: [0.9, 1.35],
    reverbDecay: [2.6, 3.6],
    reverbSend: [0.16, 0.26],
    reverbWet: [0.16, 0.26],
    cutoff: [520, 920],
    bassStrides: [2, 4],
    pulseStrides: [2, 4],
    melodyOctaves: [1, 2],
    rhythmShifts: [0, 2],
    counterChance: [0.7, 0.96],
    drumDensity: [0.65, 0.85],
    voiceEngine: "dual-osc",
    drumKit: "gated",
    pulseRole: "stab",
    saturation: [0.16, 0.26],
    drum: {
      kickStart: 172, kickEnd: 38, kickTail: 0.3,
      snareBody: 202, snareNoise: 1450, hatFrequency: 5600, openHatFrequency: 2600,
      tomStart: 172, tomEnd: 96, impactStart: 116, impactEnd: 28, noisePan: -0.2,
    },
  },
  {
    name: "signal-chase",
    scales: ["mixolydian", "major", "dorian"],
    grooves: ["pulse", "march", "shuffle"],
    grooveVariants: [1, 2],
    progressionVariants: [2, 3],
    bassRiffFamily: "octave",
    tempoBias: [2, 6],
    swing: [0.004, 0.022],
    bassTypes: ["square", "sawtooth"],
    pulseTypes: ["square", "sawtooth"],
    melodyTypes: ["square", "sawtooth"],
    counterTypes: ["square", "triangle"],
    padTypes: ["sawtooth", "square"],
    padDetunes: [[-10, -19, 16, 7], [-6, -14, 12, 5]],
    padLfoRate: [0.52, 0.82],
    padLfoDepth: [140, 250],
    padQ: [0.9, 1.6],
    delayBeats: [0.375, 0.5, 0.75],
    delayFeedback: [0.25, 0.4],
    delayWet: [0.2, 0.34],
    reverbSeconds: [0.7, 1.15],
    reverbDecay: [2, 2.9],
    reverbSend: [0.14, 0.24],
    reverbWet: [0.14, 0.25],
    cutoff: [680, 1320],
    bassStrides: [2, 4],
    pulseStrides: [1, 2],
    melodyOctaves: [2],
    rhythmShifts: [1, 2],
    counterChance: [0.38, 0.68],
    drumDensity: [0.84, 1],
    voiceEngine: "pwm",
    drumKit: "gated",
    pulseRole: "arp",
    saturation: [0.16, 0.26],
    drum: {
      kickStart: 232, kickEnd: 44, kickTail: 0.14,
      snareBody: 250, snareNoise: 2700, hatFrequency: 9000, openHatFrequency: 4200,
      tomStart: 210, tomEnd: 128, impactStart: 102, impactEnd: 36, noisePan: 0.12,
    },
  },
  {
    name: "chrome-fanfare",
    scales: ["major", "mixolydian"],
    grooves: ["pulse", "shuffle"],
    grooveVariants: [0, 1, 2],
    progressionVariants: [0, 1, 2],
    bassRiffFamily: "walking",
    tempoBias: [2, 5],
    swing: [0.006, 0.02],
    bassTypes: ["sawtooth", "square"],
    pulseTypes: ["square", "sawtooth"],
    melodyTypes: ["sawtooth", "square"],
    counterTypes: ["triangle", "square"],
    padTypes: ["sawtooth", "triangle"],
    padDetunes: [[-8, -16, 12, 6], [-5, -12, 9, 4]],
    padLfoRate: [0.38, 0.62],
    padLfoDepth: [110, 200],
    padQ: [0.8, 1.3],
    delayBeats: [0.5, 0.75],
    delayFeedback: [0.2, 0.34],
    delayWet: [0.18, 0.3],
    reverbSeconds: [0.85, 1.3],
    reverbDecay: [2.2, 3.1],
    reverbSend: [0.18, 0.28],
    reverbWet: [0.18, 0.28],
    cutoff: [740, 1280],
    bassStrides: [2, 4],
    pulseStrides: [1, 2],
    melodyOctaves: [2],
    rhythmShifts: [0, 1],
    counterChance: [0.5, 0.82],
    drumDensity: [0.88, 1],
    voiceEngine: "pwm",
    drumKit: "gated",
    pulseRole: "stab",
    saturation: [0.16, 0.26],
    drum: {
      kickStart: 198, kickEnd: 40, kickTail: 0.15,
      snareBody: 228, snareNoise: 2100, hatFrequency: 7800, openHatFrequency: 3600,
      tomStart: 188, tomEnd: 118, impactStart: 110, impactEnd: 32, noisePan: -0.06,
    },
  },
  {
    name: "low-orbit",
    scales: ["dorian", "phrygian", "natural minor"],
    grooves: ["pulse", "march"],
    grooveVariants: [0, 1],
    progressionVariants: [0, 1, 2],
    bassRiffFamily: "sparse",
    tempoBias: [-2, 2],
    swing: [0.01, 0.028],
    bassTypes: ["triangle", "sawtooth"],
    pulseTypes: ["triangle", "square"],
    melodyTypes: ["triangle", "sawtooth"],
    counterTypes: ["triangle", "square"],
    padTypes: ["triangle", "sawtooth"],
    padDetunes: [[-2, -7, 6, 2], [-4, -9, 8, 3]],
    padLfoRate: [0.14, 0.3],
    padLfoDepth: [60, 130],
    padQ: [0.4, 0.75],
    delayBeats: [0.75, 1],
    delayFeedback: [0.28, 0.42],
    delayWet: [0.22, 0.34],
    reverbSeconds: [1.1, 1.6],
    reverbDecay: [2.6, 3.6],
    reverbSend: [0.18, 0.3],
    reverbWet: [0.18, 0.3],
    cutoff: [480, 860],
    bassStrides: [2, 4],
    pulseStrides: [1, 2],
    melodyOctaves: [1, 2],
    rhythmShifts: [0, 1],
    counterChance: [0.66, 0.94],
    drumDensity: [0.6, 0.82],
    voiceEngine: "fm-bell",
    drumKit: "analog-808",
    pulseRole: "arp",
    saturation: [0.08, 0.16],
    drum: {
      kickStart: 142, kickEnd: 48, kickTail: 0.28,
      snareBody: 170, snareNoise: 1200, hatFrequency: 4800, openHatFrequency: 2200,
      tomStart: 136, tomEnd: 80, impactStart: 76, impactEnd: 22, noisePan: 0.18,
    },
  },
  {
    name: "glass-chime",
    scales: ["major", "mixolydian", "minor pentatonic"],
    grooves: ["pulse", "half-time"],
    grooveVariants: [0, 1],
    progressionVariants: [0, 2],
    bassRiffFamily: "pedal",
    tempoBias: [-1, 3],
    swing: [0.004, 0.018],
    bassTypes: ["triangle", "sine"],
    pulseTypes: ["triangle", "square"],
    melodyTypes: ["triangle", "sine"],
    counterTypes: ["triangle", "sine"],
    padTypes: ["triangle", "sine"],
    padDetunes: [[-2, -5, 4, 2], [-3, -8, 6, 2]],
    padLfoRate: [0.2, 0.4],
    padLfoDepth: [80, 150],
    padQ: [0.35, 0.7],
    delayBeats: [0.75, 1, 1.5],
    delayFeedback: [0.26, 0.4],
    delayWet: [0.2, 0.32],
    reverbSeconds: [1.0, 1.45],
    reverbDecay: [2.2, 3.2],
    reverbSend: [0.18, 0.3],
    reverbWet: [0.18, 0.28],
    cutoff: [820, 1480],
    bassStrides: [2, 4],
    pulseStrides: [1, 2],
    melodyOctaves: [2],
    rhythmShifts: [0, 1],
    counterChance: [0.58, 0.88],
    drumDensity: [0.6, 0.82],
    voiceEngine: "fm-bell",
    drumKit: "gated",
    pulseRole: "arp",
    saturation: [0.06, 0.14],
    drum: {
      kickStart: 156, kickEnd: 50, kickTail: 0.18,
      snareBody: 240, snareNoise: 2100, hatFrequency: 8600, openHatFrequency: 4100,
      tomStart: 168, tomEnd: 102, impactStart: 88, impactEnd: 30, noisePan: 0.1,
    },
  },
  {
    name: "foundry-stomp",
    scales: ["phrygian", "harmonic minor", "natural minor"],
    grooves: ["march", "half-time"],
    grooveVariants: [0, 2],
    progressionVariants: [1, 3],
    bassRiffFamily: "industrial",
    tempoBias: [0, 3],
    swing: [0, 0.01],
    bassTypes: ["square", "sawtooth"],
    pulseTypes: ["square", "sawtooth"],
    melodyTypes: ["sawtooth", "square"],
    counterTypes: ["square", "triangle"],
    padTypes: ["sawtooth", "square"],
    padDetunes: [[-11, -20, 16, 7], [-8, -16, 13, 5]],
    padLfoRate: [0.24, 0.44],
    padLfoDepth: [80, 150],
    padQ: [1.0, 1.6],
    delayBeats: [0.5, 0.75],
    delayFeedback: [0.14, 0.26],
    delayWet: [0.12, 0.22],
    reverbSeconds: [0.55, 0.95],
    reverbDecay: [2.4, 3.2],
    reverbSend: [0.1, 0.18],
    reverbWet: [0.12, 0.2],
    cutoff: [420, 780],
    bassStrides: [2, 4],
    pulseStrides: [2, 4],
    melodyOctaves: [1, 2],
    rhythmShifts: [0, 2],
    counterChance: [0.28, 0.54],
    drumDensity: [0.92, 1],
    voiceEngine: "dual-osc",
    drumKit: "industrial",
    pulseRole: "stab",
    saturation: [0.32, 0.45],
    drum: {
      kickStart: 228, kickEnd: 32, kickTail: 0.22,
      snareBody: 164, snareNoise: 1400, hatFrequency: 5400, openHatFrequency: 2500,
      tomStart: 148, tomEnd: 84, impactStart: 130, impactEnd: 24, noisePan: 0.04,
    },
  },
  {
    name: "night-raid",
    scales: ["phrygian", "harmonic minor", "dorian"],
    grooves: ["pulse", "shuffle", "half-time"],
    grooveVariants: [1, 2],
    progressionVariants: [2, 3],
    bassRiffFamily: "restless",
    tempoBias: [3, 7],
    swing: [0.01, 0.03],
    bassTypes: ["sawtooth", "square"],
    pulseTypes: ["square", "sawtooth"],
    melodyTypes: ["square", "triangle"],
    counterTypes: ["square", "sine"],
    padTypes: ["sawtooth", "triangle"],
    padDetunes: [[-13, -22, 18, 8], [-9, -17, 14, 6]],
    padLfoRate: [0.55, 0.9],
    padLfoDepth: [150, 260],
    padQ: [1.0, 1.7],
    delayBeats: [0.375, 0.5],
    delayFeedback: [0.26, 0.4],
    delayWet: [0.2, 0.34],
    reverbSeconds: [0.6, 1.05],
    reverbDecay: [1.8, 2.6],
    reverbSend: [0.12, 0.22],
    reverbWet: [0.13, 0.24],
    cutoff: [640, 1180],
    bassStrides: [2],
    pulseStrides: [1, 2],
    melodyOctaves: [2],
    rhythmShifts: [1, 2],
    counterChance: [0.4, 0.72],
    drumDensity: [0.88, 1],
    voiceEngine: "pwm",
    drumKit: "gated",
    pulseRole: "arp",
    saturation: [0.18, 0.28],
    drum: {
      kickStart: 210, kickEnd: 40, kickTail: 0.12,
      snareBody: 248, snareNoise: 2500, hatFrequency: 8800, openHatFrequency: 4000,
      tomStart: 200, tomEnd: 122, impactStart: 98, impactEnd: 34, noisePan: -0.12,
    },
  },
  {
    name: "ice-protocol",
    scales: ["dorian", "minor pentatonic", "natural minor"],
    grooves: ["half-time", "pulse", "march"],
    grooveVariants: [0, 1],
    progressionVariants: [0, 1, 2],
    bassRiffFamily: "sparse",
    tempoBias: [-2, 2],
    swing: [0.008, 0.024],
    bassTypes: ["triangle", "sawtooth"],
    pulseTypes: ["triangle", "square"],
    melodyTypes: ["triangle", "sawtooth"],
    counterTypes: ["triangle", "square"],
    padTypes: ["triangle", "sawtooth"],
    padDetunes: [[-1, -5, 4, 1], [-3, -7, 6, 2]],
    padLfoRate: [0.1, 0.26],
    padLfoDepth: [50, 110],
    padQ: [0.32, 0.65],
    delayBeats: [0.75, 1],
    delayFeedback: [0.28, 0.42],
    delayWet: [0.22, 0.34],
    reverbSeconds: [1.15, 1.7],
    reverbDecay: [2.6, 3.6],
    reverbSend: [0.18, 0.3],
    reverbWet: [0.18, 0.3],
    cutoff: [420, 780],
    bassStrides: [2, 4],
    pulseStrides: [1, 2],
    melodyOctaves: [1, 2],
    rhythmShifts: [0, 1],
    counterChance: [0.7, 0.96],
    drumDensity: [0.58, 0.78],
    voiceEngine: "fm-bell",
    drumKit: "analog-808",
    pulseRole: "arp",
    saturation: [0.08, 0.16],
    drum: {
      kickStart: 128, kickEnd: 52, kickTail: 0.32,
      snareBody: 158, snareNoise: 1050, hatFrequency: 4300, openHatFrequency: 2000,
      tomStart: 124, tomEnd: 72, impactStart: 70, impactEnd: 20, noisePan: 0.2,
    },
  },
  {
    name: "bit-garrison",
    scales: ["minor pentatonic", "major", "mixolydian"],
    grooves: ["pulse", "shuffle"],
    grooveVariants: [0, 1],
    progressionVariants: [0, 1, 2],
    bassRiffFamily: "chip-ostinato",
    tempoBias: [2, 5],
    swing: [0, 0.012],
    bassTypes: ["square", "triangle"],
    pulseTypes: ["square", "triangle"],
    melodyTypes: ["square", "triangle"],
    counterTypes: ["square", "triangle"],
    padTypes: ["square", "triangle"],
    padDetunes: [[-1, -3, 2, 1], [0, -2, 3, 1]],
    padLfoRate: [0.4, 0.7],
    padLfoDepth: [40, 90],
    padQ: [0.4, 0.8],
    delayBeats: [0.25, 0.5],
    delayFeedback: [0.08, 0.18],
    delayWet: [0.06, 0.14],
    reverbSeconds: [0.35, 0.65],
    reverbDecay: [1.2, 1.8],
    reverbSend: [0.06, 0.12],
    reverbWet: [0.06, 0.12],
    cutoff: [900, 1600],
    bassStrides: [2],
    pulseStrides: [1, 2],
    melodyOctaves: [2],
    rhythmShifts: [0, 1],
    counterChance: [0.35, 0.6],
    drumDensity: [0.86, 1],
    voiceEngine: "chip",
    drumKit: "chip-noise",
    pulseRole: "arp",
    saturation: [0.08, 0.16],
    drum: {
      kickStart: 240, kickEnd: 70, kickTail: 0.08,
      snareBody: 280, snareNoise: 3200, hatFrequency: 9800, openHatFrequency: 5200,
      tomStart: 220, tomEnd: 140, impactStart: 90, impactEnd: 40, noisePan: -0.16,
    },
  },
  {
    name: "resonant-coil",
    scales: ["natural minor", "dorian", "phrygian"],
    grooves: ["pulse", "shuffle"],
    grooveVariants: [1, 2],
    progressionVariants: [2, 3],
    bassRiffFamily: "acid-slide",
    tempoBias: [1, 5],
    swing: [0.01, 0.028],
    bassTypes: ["sawtooth", "square"],
    pulseTypes: ["sawtooth", "square"],
    melodyTypes: ["sawtooth", "square"],
    counterTypes: ["square", "triangle"],
    padTypes: ["sawtooth", "square"],
    padDetunes: [[-10, -18, 15, 7], [-7, -14, 12, 5]],
    padLfoRate: [0.7, 1.1],
    padLfoDepth: [180, 320],
    padQ: [1.4, 2.2],
    delayBeats: [0.375, 0.5],
    delayFeedback: [0.3, 0.44],
    delayWet: [0.18, 0.3],
    reverbSeconds: [0.45, 0.85],
    reverbDecay: [1.5, 2.2],
    reverbSend: [0.1, 0.18],
    reverbWet: [0.1, 0.18],
    cutoff: [700, 1400],
    bassStrides: [2],
    pulseStrides: [1],
    melodyOctaves: [2],
    rhythmShifts: [1, 2],
    counterChance: [0.3, 0.55],
    drumDensity: [0.92, 1],
    voiceEngine: "acid-res",
    drumKit: "analog-808",
    pulseRole: "arp",
    saturation: [0.22, 0.34],
    drum: {
      kickStart: 80, kickEnd: 42, kickTail: 0.28,
      snareBody: 200, snareNoise: 1800, hatFrequency: 7600, openHatFrequency: 3400,
      tomStart: 170, tomEnd: 100, impactStart: 88, impactEnd: 28, noisePan: -0.1,
    },
  },
  {
    name: "break-wire",
    scales: ["natural minor", "dorian", "blues"],
    grooves: ["breakbeat", "shuffle"],
    grooveVariants: [0, 1, 2],
    progressionVariants: [1, 2, 3],
    bassRiffFamily: "restless",
    tempoBias: [2, 6],
    swing: [0.004, 0.02],
    bassTypes: ["sawtooth", "square"],
    pulseTypes: ["square", "sawtooth"],
    melodyTypes: ["square", "sawtooth"],
    counterTypes: ["square", "triangle"],
    padTypes: ["sawtooth", "triangle"],
    padDetunes: [[-8, -16, 13, 6], [-5, -12, 10, 4]],
    padLfoRate: [0.45, 0.8],
    padLfoDepth: [110, 200],
    padQ: [0.9, 1.5],
    delayBeats: [0.375, 0.75],
    delayFeedback: [0.18, 0.32],
    delayWet: [0.14, 0.26],
    reverbSeconds: [0.5, 0.9],
    reverbDecay: [1.8, 2.6],
    reverbSend: [0.1, 0.2],
    reverbWet: [0.12, 0.22],
    cutoff: [620, 1180],
    bassStrides: [2],
    pulseStrides: [1, 2],
    melodyOctaves: [2],
    rhythmShifts: [1, 2],
    counterChance: [0.4, 0.7],
    drumDensity: [0.9, 1],
    voiceEngine: "dual-osc",
    drumKit: "analog-808",
    pulseRole: "stab",
    saturation: [0.2, 0.32],
    drum: {
      kickStart: 196, kickEnd: 38, kickTail: 0.16,
      snareBody: 220, snareNoise: 2400, hatFrequency: 8400, openHatFrequency: 3800,
      tomStart: 190, tomEnd: 112, impactStart: 100, impactEnd: 32, noisePan: 0.08,
    },
  },
  {
    name: "dune-cipher",
    scales: ["double harmonic", "phrygian", "harmonic minor"],
    grooves: ["pulse", "half-time", "march"],
    grooveVariants: [0, 1],
    progressionVariants: [0, 1, 2],
    bassRiffFamily: "descending",
    tempoBias: [-1, 3],
    swing: [0.006, 0.022],
    bassTypes: ["sawtooth", "triangle"],
    pulseTypes: ["triangle", "square"],
    melodyTypes: ["sawtooth", "triangle"],
    counterTypes: ["triangle", "sine"],
    padTypes: ["triangle", "sawtooth"],
    padDetunes: [[-4, -9, 8, 3], [-6, -12, 10, 4]],
    padLfoRate: [0.16, 0.34],
    padLfoDepth: [70, 140],
    padQ: [0.55, 1.0],
    delayBeats: [0.75, 1],
    delayFeedback: [0.24, 0.38],
    delayWet: [0.2, 0.32],
    reverbSeconds: [0.95, 1.45],
    reverbDecay: [2.4, 3.4],
    reverbSend: [0.16, 0.26],
    reverbWet: [0.16, 0.26],
    cutoff: [540, 980],
    bassStrides: [2, 4],
    pulseStrides: [2, 4],
    melodyOctaves: [1, 2],
    rhythmShifts: [0, 1],
    counterChance: [0.55, 0.85],
    drumDensity: [0.62, 0.84],
    voiceEngine: "fm-bell",
    drumKit: "gated",
    pulseRole: "stab",
    saturation: [0.12, 0.22],
    drum: {
      kickStart: 164, kickEnd: 44, kickTail: 0.22,
      snareBody: 190, snareNoise: 1500, hatFrequency: 6400, openHatFrequency: 2900,
      tomStart: 150, tomEnd: 88, impactStart: 96, impactEnd: 26, noisePan: 0.14,
    },
  },
  {
    name: "relay-dub",
    scales: ["dorian", "natural minor", "minor pentatonic"],
    grooves: ["offbeat", "half-time"],
    grooveVariants: [0, 1, 2],
    progressionVariants: [0, 1, 2],
    bassRiffFamily: "dub-space",
    tempoBias: [-3, 1],
    swing: [0.012, 0.032],
    bassTypes: ["sine", "triangle"],
    pulseTypes: ["triangle", "sine"],
    melodyTypes: ["triangle", "sine"],
    counterTypes: ["sine", "triangle"],
    padTypes: ["triangle", "sine"],
    padDetunes: [[-2, -6, 5, 2], [-3, -8, 6, 2]],
    padLfoRate: [0.12, 0.28],
    padLfoDepth: [50, 110],
    padQ: [0.35, 0.7],
    delayBeats: [0.75, 1, 1.5],
    delayFeedback: [0.38, 0.52],
    delayWet: [0.28, 0.42],
    reverbSeconds: [1.2, 1.8],
    reverbDecay: [2.8, 3.8],
    reverbSend: [0.2, 0.32],
    reverbWet: [0.2, 0.32],
    cutoff: [400, 760],
    bassStrides: [4, 8],
    pulseStrides: [2, 4],
    melodyOctaves: [1, 2],
    rhythmShifts: [0, 2],
    counterChance: [0.5, 0.82],
    drumDensity: [0.52, 0.74],
    voiceEngine: "dual-osc",
    drumKit: "analog-808",
    pulseRole: "offbeat",
    saturation: [0.1, 0.2],
    drum: {
      kickStart: 72, kickEnd: 38, kickTail: 0.36,
      snareBody: 168, snareNoise: 1100, hatFrequency: 4600, openHatFrequency: 2100,
      tomStart: 130, tomEnd: 76, impactStart: 74, impactEnd: 22, noisePan: 0.18,
    },
  },
  {
    name: "disco-command",
    scales: ["major", "mixolydian", "lydian"],
    grooves: ["four-floor", "pulse"],
    grooveVariants: [0, 1, 2],
    progressionVariants: [0, 1, 2],
    bassRiffFamily: "walking",
    tempoBias: [1, 4],
    swing: [0.004, 0.016],
    bassTypes: ["sawtooth", "square"],
    pulseTypes: ["square", "sawtooth"],
    melodyTypes: ["sawtooth", "square"],
    counterTypes: ["triangle", "square"],
    padTypes: ["sawtooth", "triangle"],
    padDetunes: [[-6, -14, 11, 5], [-4, -10, 8, 3]],
    padLfoRate: [0.35, 0.58],
    padLfoDepth: [100, 180],
    padQ: [0.7, 1.2],
    delayBeats: [0.5, 0.75],
    delayFeedback: [0.16, 0.28],
    delayWet: [0.14, 0.24],
    reverbSeconds: [0.7, 1.15],
    reverbDecay: [2.0, 2.8],
    reverbSend: [0.14, 0.24],
    reverbWet: [0.14, 0.24],
    cutoff: [780, 1340],
    bassStrides: [2],
    pulseStrides: [2, 4],
    melodyOctaves: [2],
    rhythmShifts: [0, 1],
    counterChance: [0.48, 0.78],
    drumDensity: [0.9, 1],
    voiceEngine: "pwm",
    drumKit: "gated",
    pulseRole: "stab",
    saturation: [0.14, 0.24],
    drum: {
      kickStart: 190, kickEnd: 44, kickTail: 0.14,
      snareBody: 230, snareNoise: 2000, hatFrequency: 8000, openHatFrequency: 3700,
      tomStart: 184, tomEnd: 116, impactStart: 108, impactEnd: 30, noisePan: -0.04,
    },
  },
  {
    name: "choir-vector",
    scales: ["dorian", "lydian", "major"],
    grooves: ["half-time", "pulse"],
    grooveVariants: [0, 1],
    progressionVariants: [0, 1, 2],
    bassRiffFamily: "pedal",
    tempoBias: [-2, 1],
    swing: [0.004, 0.016],
    bassTypes: ["sine", "triangle"],
    pulseTypes: ["triangle", "sine"],
    melodyTypes: ["triangle", "sine"],
    counterTypes: ["sine", "triangle"],
    padTypes: ["triangle", "sine"],
    padDetunes: [[-2, -5, 4, 2], [-1, -4, 3, 1]],
    padLfoRate: [0.08, 0.22],
    padLfoDepth: [40, 90],
    padQ: [0.28, 0.55],
    delayBeats: [1, 1.5],
    delayFeedback: [0.22, 0.36],
    delayWet: [0.18, 0.3],
    reverbSeconds: [1.3, 1.9],
    reverbDecay: [3.0, 4.0],
    reverbSend: [0.24, 0.36],
    reverbWet: [0.22, 0.34],
    cutoff: [480, 860],
    bassStrides: [4, 8],
    pulseStrides: [4],
    melodyOctaves: [1, 2],
    rhythmShifts: [0, 1],
    counterChance: [0.62, 0.92],
    drumDensity: [0.42, 0.64],
    voiceEngine: "fm-bell",
    drumKit: "analog-808",
    pulseRole: "none",
    saturation: [0.05, 0.12],
    drum: {
      kickStart: 120, kickEnd: 48, kickTail: 0.34,
      snareBody: 150, snareNoise: 980, hatFrequency: 4000, openHatFrequency: 1900,
      tomStart: 118, tomEnd: 70, impactStart: 68, impactEnd: 20, noisePan: 0.16,
    },
  },
  {
    name: "tape-static",
    scales: ["natural minor", "dorian", "blues"],
    grooves: ["offbeat", "shuffle", "half-time"],
    grooveVariants: [0, 1],
    progressionVariants: [1, 2],
    bassRiffFamily: "sparse",
    tempoBias: [-2, 2],
    swing: [0.014, 0.034],
    bassTypes: ["triangle", "sawtooth"],
    pulseTypes: ["triangle", "square"],
    melodyTypes: ["triangle", "square"],
    counterTypes: ["triangle", "sine"],
    padTypes: ["triangle", "sawtooth"],
    padDetunes: [[-12, -22, 18, 8], [-9, -16, 14, 6]],
    padLfoRate: [0.2, 0.4],
    padLfoDepth: [80, 160],
    padQ: [0.6, 1.1],
    delayBeats: [0.5, 0.75],
    delayFeedback: [0.2, 0.34],
    delayWet: [0.16, 0.28],
    reverbSeconds: [0.4, 0.75],
    reverbDecay: [1.4, 2.2],
    reverbSend: [0.1, 0.18],
    reverbWet: [0.1, 0.18],
    cutoff: [380, 720],
    bassStrides: [2, 4],
    pulseStrides: [2, 4],
    melodyOctaves: [1, 2],
    rhythmShifts: [1, 2],
    counterChance: [0.36, 0.64],
    drumDensity: [0.7, 0.9],
    voiceEngine: "chip",
    drumKit: "chip-noise",
    pulseRole: "offbeat",
    saturation: [0.28, 0.4],
    drum: {
      kickStart: 160, kickEnd: 46, kickTail: 0.18,
      snareBody: 176, snareNoise: 1400, hatFrequency: 5200, openHatFrequency: 2500,
      tomStart: 144, tomEnd: 86, impactStart: 82, impactEnd: 24, noisePan: 0.06,
    },
  },
];

const MELODY_DEFAULT = [true, true, true, true, false, true, true, true] as const;
const PULSE_DEFAULT = [true, true, true, true, true, true, true, true] as const;
const COUNTER_DEFAULT = [false, false, false, true, false, false, true, false] as const;
const HOLD_DEFAULT = [false, false, false, false, true, false, false, false] as const;
const HAT_DEFAULT = [2, 2, 2, 2, 4, 2, 1, 2] as const;
const FILL_DEFAULT = ["tom-only", "snare-tom", "snare-tom", "snare-tom", "hat-chatter", "snare-tom", "kick-roll", "snare-tom"] as const;

const ARRANGEMENTS: readonly MusicArrangementProfile[] = [
  {
    name: "slow-burn",
    bassStrides: [8, 8, 4, 4, 8, 4, 4, 4],
    pulseStrides: [4, 4, 2, 2, 4, 2, 2, 2],
    melodyEnabled: MELODY_DEFAULT,
    pulseEnabled: PULSE_DEFAULT,
    counterEnabled: COUNTER_DEFAULT,
    holdBass: HOLD_DEFAULT,
    hatStride: HAT_DEFAULT,
    fillStyle: FILL_DEFAULT,
    echoMelody: false,
    melodyDegreeOffset: 0,
    rhythmOffset: 0,
    drumDensity: [0.58, 0.72, 0.92, 0.88, 0.38, 0.82, 1, 0.86],
  },
  {
    name: "forward-drive",
    bassStrides: [2, 2, 2, 2, 4, 2, 2, 2],
    pulseStrides: [2, 2, 2, 2, 4, 2, 1, 2],
    melodyEnabled: MELODY_DEFAULT,
    pulseEnabled: PULSE_DEFAULT,
    counterEnabled: COUNTER_DEFAULT,
    holdBass: HOLD_DEFAULT,
    hatStride: [2, 2, 2, 2, 4, 2, 1, 2],
    fillStyle: ["snare-tom", "snare-tom", "kick-roll", "snare-tom", "hat-chatter", "snare-tom", "kick-roll", "snare-tom"],
    echoMelody: false,
    melodyDegreeOffset: 1,
    rhythmOffset: 1,
    drumDensity: [0.78, 0.94, 1, 0.96, 0.45, 1, 1, 0.95],
  },
  {
    name: "syncopated-strike",
    bassStrides: [4, 2, 2, 2, 4, 2, 2, 2],
    pulseStrides: [2, 1, 1, 2, 4, 1, 1, 1],
    melodyEnabled: MELODY_DEFAULT,
    pulseEnabled: PULSE_DEFAULT,
    counterEnabled: [false, true, false, true, false, true, true, false],
    holdBass: HOLD_DEFAULT,
    hatStride: [2, 2, 2, 2, 4, 1, 1, 2],
    fillStyle: ["hat-chatter", "snare-tom", "snare-tom", "kick-roll", "tom-only", "snare-tom", "kick-roll", "snare-tom"],
    echoMelody: false,
    melodyDegreeOffset: -1,
    rhythmOffset: 2,
    drumDensity: [0.72, 1, 0.96, 1, 0.4, 1, 1, 1],
  },
  {
    name: "ghost-signal",
    bassStrides: [8, 8, 8, 4, 8, 4, 4, 2],
    pulseStrides: [4, 4, 4, 2, 4, 2, 2, 1],
    melodyEnabled: MELODY_DEFAULT,
    pulseEnabled: [true, true, true, true, false, true, true, true],
    counterEnabled: [false, false, true, true, false, false, true, true],
    holdBass: HOLD_DEFAULT,
    hatStride: [4, 4, 2, 2, 4, 2, 1, 2],
    fillStyle: ["tom-only", "hat-chatter", "snare-tom", "hat-chatter", "hat-chatter", "tom-only", "snare-tom", "snare-tom"],
    echoMelody: false,
    melodyDegreeOffset: 2,
    rhythmOffset: 3,
    drumDensity: [0.48, 0.58, 0.72, 0.64, 0.28, 0.68, 0.88, 0.76],
  },
  {
    name: "bass-siege",
    bassStrides: [2, 2, 2, 2, 2, 2, 2, 2],
    pulseStrides: [4, 4, 2, 2, 4, 2, 2, 1],
    melodyEnabled: MELODY_DEFAULT,
    pulseEnabled: [true, false, true, true, true, true, true, true],
    counterEnabled: [false, false, false, true, false, false, true, false],
    holdBass: HOLD_DEFAULT,
    hatStride: HAT_DEFAULT,
    fillStyle: ["snare-tom", "snare-tom", "snare-tom", "snare-tom", "tom-only", "kick-roll", "kick-roll", "snare-tom"],
    echoMelody: false,
    melodyDegreeOffset: 0,
    rhythmOffset: 0,
    drumDensity: [0.72, 0.86, 0.92, 0.9, 0.46, 0.92, 1, 0.9],
  },
  {
    name: "wide-open",
    bassStrides: [8, 4, 4, 4, 8, 4, 2, 4],
    pulseStrides: [4, 2, 2, 2, 4, 2, 1, 2],
    melodyEnabled: MELODY_DEFAULT,
    pulseEnabled: PULSE_DEFAULT,
    counterEnabled: [false, true, false, true, false, false, true, false],
    holdBass: HOLD_DEFAULT,
    hatStride: [4, 2, 2, 2, 4, 2, 1, 2],
    fillStyle: FILL_DEFAULT,
    echoMelody: false,
    melodyDegreeOffset: -2,
    rhythmOffset: 1,
    drumDensity: [0.55, 0.76, 0.84, 0.78, 0.34, 0.82, 0.94, 0.8],
  },
  {
    name: "panic-run",
    bassStrides: [2, 2, 2, 2, 2, 2, 2, 2],
    pulseStrides: [2, 1, 1, 1, 2, 1, 1, 1],
    melodyEnabled: [false, true, true, true, true, true, true, true],
    pulseEnabled: PULSE_DEFAULT,
    counterEnabled: [false, true, true, true, false, true, true, true],
    holdBass: [false, false, false, false, false, false, false, false],
    hatStride: [2, 2, 2, 1, 2, 1, 1, 1],
    fillStyle: ["kick-roll", "snare-tom", "kick-roll", "snare-tom", "snare-tom", "kick-roll", "kick-roll", "snare-tom"],
    echoMelody: false,
    melodyDegreeOffset: 2,
    rhythmOffset: 2,
    drumDensity: [0.92, 1, 1, 1, 0.72, 1, 1, 1],
  },
  {
    name: "command-theme",
    bassStrides: [4, 2, 4, 2, 4, 2, 2, 2],
    pulseStrides: [2, 2, 1, 2, 4, 2, 1, 1],
    melodyEnabled: MELODY_DEFAULT,
    pulseEnabled: PULSE_DEFAULT,
    counterEnabled: COUNTER_DEFAULT,
    holdBass: HOLD_DEFAULT,
    hatStride: [2, 2, 2, 2, 4, 2, 1, 1],
    fillStyle: ["snare-tom", "snare-tom", "snare-tom", "snare-tom", "hat-chatter", "snare-tom", "kick-roll", "kick-roll"],
    echoMelody: false,
    melodyDegreeOffset: 1,
    rhythmOffset: 3,
    drumDensity: [0.68, 0.9, 0.86, 0.92, 0.38, 0.9, 1, 0.94],
  },
  {
    name: "half-time-break",
    bassStrides: [4, 2, 2, 4, 8, 4, 2, 4],
    pulseStrides: [4, 2, 2, 2, 4, 4, 1, 2],
    melodyEnabled: [false, true, true, true, false, true, true, true],
    pulseEnabled: [true, true, true, true, false, true, true, true],
    counterEnabled: [false, false, true, true, false, false, true, false],
    holdBass: [false, false, false, false, true, false, false, false],
    hatStride: [4, 2, 2, 2, 4, 4, 1, 2],
    fillStyle: ["tom-only", "snare-tom", "snare-tom", "hat-chatter", "hat-chatter", "tom-only", "kick-roll", "snare-tom"],
    echoMelody: false,
    melodyDegreeOffset: 0,
    rhythmOffset: 1,
    drumDensity: [0.5, 0.84, 0.9, 0.8, 0.22, 0.7, 1, 0.86],
  },
  {
    name: "call-and-echo",
    bassStrides: [4, 2, 2, 2, 8, 2, 2, 2],
    pulseStrides: [4, 2, 2, 2, 4, 2, 1, 2],
    melodyEnabled: [false, true, true, true, false, true, true, true],
    pulseEnabled: PULSE_DEFAULT,
    counterEnabled: [false, true, false, true, false, true, true, false],
    holdBass: HOLD_DEFAULT,
    hatStride: HAT_DEFAULT,
    fillStyle: ["hat-chatter", "snare-tom", "snare-tom", "snare-tom", "tom-only", "snare-tom", "kick-roll", "snare-tom"],
    echoMelody: true,
    melodyDegreeOffset: 1,
    rhythmOffset: 2,
    drumDensity: [0.58, 0.88, 0.94, 0.9, 0.34, 0.92, 1, 0.9],
  },
  {
    name: "double-drop",
    bassStrides: [4, 2, 2, 2, 8, 8, 2, 2],
    pulseStrides: [4, 2, 2, 2, 4, 4, 1, 2],
    melodyEnabled: [false, true, true, true, false, false, true, true],
    pulseEnabled: [true, true, true, true, true, false, true, true],
    counterEnabled: [false, false, false, true, false, false, true, true],
    holdBass: [false, false, false, false, true, true, false, false],
    hatStride: [2, 2, 2, 2, 4, 4, 1, 2],
    fillStyle: ["snare-tom", "snare-tom", "snare-tom", "hat-chatter", "hat-chatter", "tom-only", "kick-roll", "snare-tom"],
    echoMelody: false,
    melodyDegreeOffset: -1,
    rhythmOffset: 0,
    drumDensity: [0.6, 0.9, 0.94, 0.88, 0.28, 0.18, 1, 0.92],
  },
  {
    name: "anthem-lift",
    bassStrides: [4, 2, 2, 4, 8, 2, 2, 2],
    pulseStrides: [4, 2, 1, 2, 4, 2, 1, 1],
    melodyEnabled: [false, true, true, true, false, true, true, true],
    pulseEnabled: PULSE_DEFAULT,
    counterEnabled: [false, false, true, true, false, true, true, true],
    holdBass: HOLD_DEFAULT,
    hatStride: [2, 2, 2, 2, 4, 2, 1, 1],
    fillStyle: ["tom-only", "snare-tom", "snare-tom", "snare-tom", "hat-chatter", "snare-tom", "kick-roll", "kick-roll"],
    echoMelody: false,
    melodyDegreeOffset: 2,
    rhythmOffset: 1,
    drumDensity: [0.55, 0.82, 0.96, 0.88, 0.32, 0.9, 1, 0.96],
  },
  {
    name: "melody-late",
    bassStrides: [8, 4, 4, 2, 8, 2, 2, 2],
    pulseStrides: [4, 4, 2, 2, 4, 2, 1, 2],
    melodyEnabled: [false, false, true, true, false, true, true, true],
    pulseEnabled: PULSE_DEFAULT,
    counterEnabled: [false, false, false, true, false, true, true, true],
    holdBass: [true, false, false, false, true, false, false, false],
    hatStride: [4, 2, 2, 2, 4, 2, 1, 2],
    fillStyle: ["tom-only", "hat-chatter", "snare-tom", "snare-tom", "hat-chatter", "snare-tom", "kick-roll", "snare-tom"],
    echoMelody: false,
    melodyDegreeOffset: 1,
    rhythmOffset: 2,
    drumDensity: [0.5, 0.66, 0.78, 0.92, 0.3, 0.9, 1, 0.92],
  },
  {
    name: "drums-out",
    bassStrides: [8, 4, 2, 2, 8, 2, 2, 2],
    pulseStrides: [4, 2, 2, 1, 4, 2, 1, 2],
    melodyEnabled: [false, true, true, true, false, true, true, true],
    pulseEnabled: [false, true, true, true, false, true, true, true],
    counterEnabled: [false, false, true, true, false, true, true, false],
    holdBass: [true, false, false, false, true, false, false, false],
    hatStride: [4, 4, 2, 2, 4, 2, 1, 2],
    fillStyle: ["tom-only", "tom-only", "snare-tom", "kick-roll", "hat-chatter", "snare-tom", "kick-roll", "snare-tom"],
    echoMelody: false,
    melodyDegreeOffset: 0,
    rhythmOffset: 1,
    drumDensity: [0.32, 0.58, 0.88, 0.94, 0.22, 0.92, 1, 0.9],
  },
  {
    name: "inverted-hold",
    bassStrides: [8, 2, 2, 8, 4, 2, 8, 2],
    pulseStrides: [4, 2, 2, 4, 4, 2, 1, 2],
    melodyEnabled: [true, true, true, true, true, true, false, true],
    pulseEnabled: [false, true, true, true, true, true, true, true],
    counterEnabled: [true, false, true, true, false, true, false, true],
    holdBass: [true, false, false, true, false, false, true, false],
    hatStride: [4, 2, 2, 4, 2, 2, 1, 2],
    fillStyle: ["hat-chatter", "snare-tom", "kick-roll", "tom-only", "snare-tom", "snare-tom", "kick-roll", "snare-tom"],
    echoMelody: false,
    melodyDegreeOffset: -1,
    rhythmOffset: 3,
    drumDensity: [0.52, 0.88, 0.94, 0.4, 0.74, 0.92, 0.48, 0.96],
  },
  {
    name: "echo-canon",
    bassStrides: [4, 2, 2, 2, 8, 2, 2, 2],
    pulseStrides: [4, 2, 1, 2, 4, 2, 1, 2],
    melodyEnabled: [false, true, true, true, false, true, true, true],
    pulseEnabled: PULSE_DEFAULT,
    counterEnabled: [false, true, true, true, false, true, true, false],
    holdBass: HOLD_DEFAULT,
    hatStride: [2, 2, 2, 2, 4, 2, 1, 2],
    fillStyle: ["hat-chatter", "snare-tom", "snare-tom", "kick-roll", "tom-only", "snare-tom", "kick-roll", "snare-tom"],
    echoMelody: true,
    melodyDegreeOffset: 2,
    rhythmOffset: 1,
    drumDensity: [0.5, 0.86, 0.94, 0.9, 0.3, 0.92, 1, 0.9],
  },
];

function arrangementFor(cue: MusicCue, seed: number, missionIndex: number): MusicArrangementProfile {
  const tieRng = assignmentRng(seed, cue, "music-arrangement-order");
  const ctx = musicMissionContext(seed, missionIndex);
  if (cue !== "mission" || missionIndex < 0) {
    return pickBestByScore(ARRANGEMENTS, (item) => arrangementAffinityScore(item.name, ctx), tieRng.fork(String(missionIndex)));
  }
  return pickAssignedItem(
    ARRANGEMENTS,
    campaignMusicContexts(seed),
    missionIndex,
    (item, mission) => arrangementAffinityScore(item.name, mission),
    tieRng,
    ctx,
  );
}

const BASS_RIFF_FAMILIES: Record<MusicBassRiffFamily, readonly (readonly BassHit[])[]> = {
  classic: BASS_RIFFS,
  industrial: [
    [{ tone: 0, oct: 0 }, null, { tone: 0, oct: 0 }, { tone: 2, oct: 0 }, { tone: 0, oct: 0 }, null, { tone: 3, oct: 0 }, { tone: 0, oct: 1 }],
    [{ tone: 0, oct: 0 }, { tone: 0, oct: 0 }, null, { tone: 2, oct: 0 }, { tone: 0, oct: 0 }, { tone: 0, oct: 1 }, null, { tone: 2, oct: 0 }],
    [{ tone: 0, oct: 0 }, null, null, { tone: 2, oct: 0 }, { tone: 0, oct: 0 }, null, { tone: 1, oct: 0 }, { tone: 0, oct: 1 }],
  ],
  syncopated: [
    [{ tone: 0, oct: 0 }, null, { tone: 2, oct: 0 }, null, { tone: 0, oct: 1 }, { tone: 3, oct: 0 }, null, { tone: 2, oct: 0 }],
    [{ tone: 0, oct: 0 }, { tone: 2, oct: 0 }, null, { tone: 0, oct: 1 }, null, { tone: 3, oct: 0 }, { tone: 2, oct: 0 }, null],
    [{ tone: 0, oct: 0 }, null, { tone: 1, oct: 0 }, { tone: 2, oct: 0 }, null, { tone: 0, oct: 1 }, { tone: 3, oct: 0 }, null],
  ],
  octave: [
    [{ tone: 0, oct: 0 }, { tone: 0, oct: 1 }, { tone: 0, oct: 0 }, { tone: 0, oct: 1 }, { tone: 2, oct: 0 }, { tone: 2, oct: 1 }, { tone: 0, oct: 0 }, { tone: 0, oct: 1 }],
    [{ tone: 0, oct: 0 }, { tone: 2, oct: 0 }, { tone: 0, oct: 1 }, { tone: 2, oct: 1 }, { tone: 0, oct: 0 }, { tone: 3, oct: 0 }, { tone: 0, oct: 1 }, { tone: 2, oct: 0 }],
  ],
  sparse: [
    [{ tone: 0, oct: 0 }, null, { tone: 0, oct: 0 }, { tone: 2, oct: 0 }, null, { tone: 0, oct: 1 }, { tone: 2, oct: 0 }, null],
    [{ tone: 0, oct: 0 }, null, { tone: 3, oct: 0 }, { tone: 0, oct: 0 }, null, { tone: 2, oct: 0 }, { tone: 0, oct: 1 }, { tone: 2, oct: 0 }],
  ],
  descending: [
    [{ tone: 0, oct: 0 }, { tone: 3, oct: 0 }, { tone: 2, oct: 0 }, { tone: 1, oct: 0 }, { tone: 0, oct: 1 }, { tone: 3, oct: 0 }, { tone: 2, oct: 0 }, { tone: 0, oct: 0 }],
    [{ tone: 0, oct: 0 }, null, { tone: 3, oct: 0 }, { tone: 2, oct: 0 }, { tone: 1, oct: 0 }, null, { tone: 0, oct: 1 }, { tone: 0, oct: 0 }],
  ],
  restless: [
    [{ tone: 0, oct: 0 }, { tone: 2, oct: 0 }, null, { tone: 1, oct: 1 }, { tone: 3, oct: 0 }, { tone: 0, oct: 1 }, { tone: 2, oct: 0 }, { tone: 0, oct: 1 }],
    [{ tone: 0, oct: 0 }, null, { tone: 2, oct: 0 }, { tone: 3, oct: 0 }, { tone: 0, oct: 1 }, { tone: 1, oct: 0 }, null, { tone: 2, oct: 0 }],
    [{ tone: 0, oct: 0 }, { tone: 3, oct: 0 }, null, { tone: 0, oct: 1 }, { tone: 2, oct: 0 }, null, { tone: 1, oct: 1 }, { tone: 0, oct: 0 }],
  ],
  walking: [
    [{ tone: 0, oct: 0 }, { tone: 1, oct: 0 }, { tone: 2, oct: 0 }, { tone: 3, oct: 0 }, { tone: 4, oct: 0 }, { tone: 3, oct: 0 }, { tone: 2, oct: 0 }, { tone: 1, oct: 0 }],
    [{ tone: 0, oct: 0 }, { tone: 2, oct: 0 }, { tone: 3, oct: 0 }, { tone: 2, oct: 0 }, { tone: 0, oct: 1 }, { tone: 3, oct: 0 }, { tone: 2, oct: 0 }, { tone: 0, oct: 0 }],
    [{ tone: 0, oct: 0 }, { tone: 1, oct: 0 }, null, { tone: 2, oct: 0 }, { tone: 3, oct: 0 }, { tone: 2, oct: 0 }, { tone: 1, oct: 0 }, { tone: 0, oct: 1 }],
  ],
  pedal: [
    [{ tone: 0, oct: 0 }, null, { tone: 0, oct: 0 }, null, { tone: 0, oct: 0 }, null, { tone: 2, oct: 0 }, { tone: 0, oct: 1 }],
    [{ tone: 0, oct: 0 }, { tone: 0, oct: 0 }, null, { tone: 0, oct: 1 }, { tone: 0, oct: 0 }, null, { tone: 3, oct: 0 }, null],
    [{ tone: 0, oct: 0 }, null, null, { tone: 0, oct: 0 }, { tone: 0, oct: 1 }, null, { tone: 0, oct: 0 }, { tone: 2, oct: 0 }],
  ],
  "acid-slide": [
    [{ tone: 0, oct: 0 }, { tone: 1, oct: 0 }, { tone: 2, oct: 0 }, { tone: 3, oct: 0 }, { tone: 0, oct: 1 }, { tone: 2, oct: 0 }, { tone: 1, oct: 0 }, { tone: 0, oct: 0 }],
    [{ tone: 0, oct: 0 }, null, { tone: 2, oct: 0 }, { tone: 3, oct: 1 }, { tone: 1, oct: 0 }, { tone: 0, oct: 1 }, { tone: 2, oct: 0 }, null],
    [{ tone: 0, oct: 1 }, { tone: 0, oct: 0 }, { tone: 3, oct: 0 }, { tone: 2, oct: 0 }, { tone: 1, oct: 1 }, { tone: 0, oct: 0 }, { tone: 2, oct: 1 }, { tone: 0, oct: 0 }],
  ],
  "chip-ostinato": [
    [{ tone: 0, oct: 0 }, { tone: 0, oct: 1 }, { tone: 0, oct: 0 }, { tone: 2, oct: 0 }, { tone: 0, oct: 0 }, { tone: 0, oct: 1 }, { tone: 3, oct: 0 }, { tone: 0, oct: 1 }],
    [{ tone: 0, oct: 0 }, { tone: 2, oct: 0 }, { tone: 0, oct: 1 }, { tone: 0, oct: 0 }, { tone: 3, oct: 0 }, { tone: 0, oct: 1 }, { tone: 2, oct: 0 }, { tone: 0, oct: 0 }],
    [{ tone: 0, oct: 1 }, { tone: 0, oct: 0 }, { tone: 0, oct: 1 }, { tone: 2, oct: 0 }, { tone: 0, oct: 1 }, { tone: 3, oct: 0 }, { tone: 0, oct: 0 }, { tone: 2, oct: 1 }],
  ],
  "dub-space": [
    [{ tone: 0, oct: 0 }, null, null, { tone: 0, oct: 0 }, null, { tone: 2, oct: 0 }, null, { tone: 0, oct: 1 }],
    [{ tone: 0, oct: 0 }, null, { tone: 0, oct: 1 }, null, null, { tone: 3, oct: 0 }, null, { tone: 0, oct: 0 }],
    [{ tone: 0, oct: 0 }, null, null, null, { tone: 0, oct: 1 }, null, { tone: 2, oct: 0 }, { tone: 0, oct: 0 }],
  ],
};

export function bassRiffsFor(family: MusicBassRiffFamily): readonly (readonly BassHit[])[] {
  return BASS_RIFF_FAMILIES[family];
}

function rangeValue(rng: Rng, range: Range): number {
  return range[0] + rng.next() * (range[1] - range[0]);
}

function integerValue(rng: Rng, range: Range): number {
  return Math.round(rangeValue(rng, range));
}

function stylePoolFor(cue: MusicCue): readonly StyleBlueprint[] {
  if (cue === "defeat") {
    return STYLE_BLUEPRINTS.filter((style) => ["industrial-march", "cinematic-tension", "low-orbit", "ice-protocol", "foundry-stomp", "tape-static", "choir-vector"].includes(style.name));
  }
  if (cue === "victory") {
    return STYLE_BLUEPRINTS.filter((style) => ["neon-arpeggio", "orbital-drift", "signal-chase", "chrome-fanfare", "glass-chime", "disco-command", "bit-garrison"].includes(style.name));
  }
  if (cue === "briefing") {
    return STYLE_BLUEPRINTS.filter((style) => ["orbital-drift", "cinematic-tension", "neon-arpeggio", "low-orbit", "ice-protocol", "glass-chime", "choir-vector", "relay-dub", "dune-cipher"].includes(style.name));
  }
  return STYLE_BLUEPRINTS;
}

function selectStyleBlueprint(cue: MusicCue, seed: number, missionIndex: number): StyleBlueprint {
  const pool = stylePoolFor(cue);
  const tieRng = assignmentRng(seed, cue, "music-style-order");
  const ctx = musicMissionContext(seed, Math.max(0, missionIndex));
  if (cue !== "mission" || missionIndex < 0) {
    return pickBestByScore(pool, (item) => styleAffinityScore(item.name, ctx), tieRng.fork(String(missionIndex)));
  }
  return pickAssignedItem(
    pool,
    campaignMusicContexts(seed),
    missionIndex,
    (item, mission) => styleAffinityScore(item.name, mission),
    tieRng,
    ctx,
  );
}

export function createMusicStyle(cue: MusicCue, rng: Rng, seed = 0, missionIndex = 0): MusicStyleProfile {
  const textureRng = rng.fork("texture");
  const blueprint = selectStyleBlueprint(cue, seed, missionIndex);
  const context = musicMissionContext(seed, missionIndex);
  const profile: MusicStyleProfile = {
    name: blueprint.name,
    scalePool: blueprint.scales,
    groove: textureRng.pick(blueprint.grooves),
    grooveVariant: textureRng.pick(blueprint.grooveVariants),
    progressionVariant: textureRng.pick(blueprint.progressionVariants),
    bassRiffFamily: blueprint.bassRiffFamily,
    arrangement: arrangementFor(cue, seed, missionIndex),
    tempoBias: integerValue(textureRng, blueprint.tempoBias),
    swing: rangeValue(textureRng, blueprint.swing),
    bassType: textureRng.pick(blueprint.bassTypes),
    pulseType: textureRng.pick(blueprint.pulseTypes),
    melodyType: textureRng.pick(blueprint.melodyTypes),
    counterType: textureRng.pick(blueprint.counterTypes),
    padType: textureRng.pick(blueprint.padTypes),
    padDetune: textureRng.pick(blueprint.padDetunes) as [number, number, number, number],
    padLfoRate: rangeValue(textureRng, blueprint.padLfoRate),
    padLfoDepth: rangeValue(textureRng, blueprint.padLfoDepth),
    padQ: rangeValue(textureRng, blueprint.padQ),
    delayBeats: textureRng.pick(blueprint.delayBeats),
    delayFeedback: rangeValue(textureRng, blueprint.delayFeedback),
    delayWet: rangeValue(textureRng, blueprint.delayWet),
    reverbSeconds: rangeValue(textureRng, blueprint.reverbSeconds),
    reverbDecay: rangeValue(textureRng, blueprint.reverbDecay),
    reverbSend: rangeValue(textureRng, blueprint.reverbSend),
    reverbWet: rangeValue(textureRng, blueprint.reverbWet),
    cutoffMin: blueprint.cutoff[0],
    cutoffMax: blueprint.cutoff[1],
    bassStride: textureRng.pick(blueprint.bassStrides),
    pulseStride: textureRng.pick(blueprint.pulseStrides),
    melodyOctave: textureRng.pick(blueprint.melodyOctaves),
    rhythmShift: textureRng.pick(blueprint.rhythmShifts),
    counterChance: rangeValue(textureRng, blueprint.counterChance),
    drumDensity: rangeValue(textureRng, blueprint.drumDensity),
    voiceEngine: blueprint.voiceEngine,
    drumKit: blueprint.drumKit,
    pulseRole: blueprint.pulseRole,
    saturationAmount: rangeValue(textureRng, blueprint.saturation),
    drum: { ...blueprint.drum },
  };
  return applyMissionTints(profile, context);
}

export function styleRng(seed: number, cue: MusicCue, missionIndex: number): Rng {
  return createRng(seed, `music-style:${cue}:${missionIndex}`);
}
