import { readFileSync, writeFileSync } from "node:fs";
import { join, relative } from "node:path";
import sharp from "sharp";
import { PORTRAIT_ASSETS, PORTRAIT_FRAME_COUNT } from "../lib/gen/portraitCatalog";
import { PORTRAIT_MOUTH_CALIBRATION_OVERRIDES } from "../lib/gen/portraitCalibrationOverrides";
import {
  measurePortraitOffset,
  portraitRegistrationWindow,
  resolvePortraitBlinkAlignment,
} from "../lib/render/portraits/alignment";
import { detectPortraitMouthClip } from "../lib/render/portraits/mouthDetection";
import { lumaBuffer } from "../lib/render/portraits/luma";
import {
  PORTRAIT_MEASURE_HEIGHT,
  PORTRAIT_MEASURE_WIDTH,
  type PortraitClip,
  type PortraitOffset,
} from "../lib/render/portraits/types";
import { portraitFrameRect } from "../lib/render/portraits/drawing";
import type { PortraitMouthCalibration } from "../lib/gen/portraitCalibration";

const CALIBRATION_FILE = join(process.cwd(), "lib/gen/portraitCalibration.generated.ts");
const MOUTH_SIGNAL_THRESHOLD = 4;
const MAX_SUPPORTED_FRAME_DRIFT = 10;
const MOUTH_REGION = {
  cx0: 0.35,
  cx1: 0.65,
  cy0: 0.54,
  cy1: 0.9,
} as const;

type CalibratedPortrait = {
  id: string;
  calibration: PortraitMouthCalibration;
  talkOffset: PortraitOffset;
  blinkOffset: PortraitOffset;
  mouthSignal: number;
  source: "detected" | "manual";
  note?: string;
};

type CalibrationFailure = {
  id: string;
  reason: string;
  manualOverride: boolean;
};

function formatNumber(value: number): string {
  const rounded = Math.round(value * 1_000_000) / 1_000_000;
  return Object.is(rounded, -0) ? "0" : String(rounded);
}

function formatOffset(offset: PortraitOffset): string {
  return `{ dx: ${formatNumber(offset.dx)}, dy: ${formatNumber(offset.dy)} }`;
}

function formatClip(clip: PortraitClip): string {
  return `{ cx: ${formatNumber(clip.cx)}, cy: ${formatNumber(clip.cy)}, rx: ${formatNumber(clip.rx)}, ry: ${formatNumber(clip.ry)} }`;
}

function formatCalibration(calibration: PortraitMouthCalibration): string {
  return `{ clip: ${formatClip(calibration.clip)}, talkOffset: ${formatOffset(calibration.talkOffset)} }`;
}

function translateRgba(
  rgba: Buffer,
  width: number,
  height: number,
  offset: PortraitOffset,
): Buffer {
  const translated = Buffer.alloc(rgba.length);
  for (let y = 0; y < height; y += 1) {
    for (let x = 0; x < width; x += 1) {
      const sourceX = x - offset.dx;
      const sourceY = y - offset.dy;
      if (sourceX < 0 || sourceX >= width || sourceY < 0 || sourceY >= height) continue;
      const targetIndex = (y * width + x) * 4;
      const sourceIndex = (Math.round(sourceY) * width + Math.round(sourceX)) * 4;
      translated[targetIndex] = rgba[sourceIndex] ?? 0;
      translated[targetIndex + 1] = rgba[sourceIndex + 1] ?? 0;
      translated[targetIndex + 2] = rgba[sourceIndex + 2] ?? 0;
      translated[targetIndex + 3] = rgba[sourceIndex + 3] ?? 0;
    }
  }
  return translated;
}

function generatedFileText(results: readonly CalibratedPortrait[]): string {
  const entries = results
    .map(({ id, calibration }) => `  ${JSON.stringify(id)}: ${formatCalibration(calibration)},`)
    .join("\n");
  return `/** Generated by yarn calibrate-portraits --write. Do not edit by hand. */
import type { PortraitMouthCalibration } from "./portraitCalibration";

export const GENERATED_PORTRAIT_MOUTH_CALIBRATIONS = {
${entries}
} as const satisfies Readonly<Record<string, PortraitMouthCalibration>>;
`;
}

function frameExtract(
  imageWidth: number,
  imageHeight: number,
  frame: number,
): { left: number; top: number; width: number; height: number } {
  const source = portraitFrameRect(
    imageWidth,
    imageHeight,
    PORTRAIT_FRAME_COUNT,
    frame,
    PORTRAIT_MEASURE_WIDTH,
    PORTRAIT_MEASURE_HEIGHT,
  );
  return {
    // Canvas drawImage rounds the source rectangle in drawPortraitFrame. Keep
    // the offline crop byte-for-byte aligned with that renderer behavior.
    left: Math.round(source.sx),
    top: Math.round(source.sy),
    width: Math.round(source.sw),
    height: Math.round(source.sh),
  };
}

async function readFrame(
  file: string,
  imageWidth: number,
  imageHeight: number,
  frame: number,
): Promise<Buffer> {
  return sharp(file)
    .extract(frameExtract(imageWidth, imageHeight, frame))
    .resize(PORTRAIT_MEASURE_WIDTH, PORTRAIT_MEASURE_HEIGHT, { fit: "fill" })
    .ensureAlpha()
    .raw()
    .toBuffer();
}

function maxMouthSignal(idleRgba: ArrayLike<number>, talkRgba: ArrayLike<number>): number {
  const idle = lumaBuffer(idleRgba, PORTRAIT_MEASURE_WIDTH, PORTRAIT_MEASURE_HEIGHT);
  const talk = lumaBuffer(talkRgba, PORTRAIT_MEASURE_WIDTH, PORTRAIT_MEASURE_HEIGHT);
  const x0 = Math.floor(PORTRAIT_MEASURE_WIDTH * 0.32);
  const x1 = Math.ceil(PORTRAIT_MEASURE_WIDTH * 0.68);
  const y0 = Math.floor(PORTRAIT_MEASURE_HEIGHT * 0.54);
  const y1 = Math.ceil(PORTRAIT_MEASURE_HEIGHT * 0.9);
  let best = 0;
  for (let y = y0; y < y1; y += 1) {
    let total = 0;
    for (let x = x0; x < x1; x += 1) {
      total += Math.abs(idle[y * PORTRAIT_MEASURE_WIDTH + x]! - talk[y * PORTRAIT_MEASURE_WIDTH + x]!);
    }
    best = Math.max(best, total / (x1 - x0));
  }
  return best;
}

function validateClip(clip: PortraitClip, mouthSignal: number): string[] {
  const failures: string[] = [];
  if (mouthSignal < MOUTH_SIGNAL_THRESHOLD) {
    failures.push(`mouth signal ${mouthSignal.toFixed(2)} < ${MOUTH_SIGNAL_THRESHOLD}`);
  }
  if (clip.cx < MOUTH_REGION.cx0 || clip.cx > MOUTH_REGION.cx1 || clip.cy < MOUTH_REGION.cy0 || clip.cy > MOUTH_REGION.cy1) {
    failures.push(
      `mouth ${formatClip(clip)} is outside expected face region x ${MOUTH_REGION.cx0}-${MOUTH_REGION.cx1}, y ${MOUTH_REGION.cy0}-${MOUTH_REGION.cy1}`,
    );
  }
  if (
    clip.cx - clip.rx < 0 ||
    clip.cx + clip.rx > 1 ||
    clip.cy - clip.ry < 0 ||
    clip.cy + clip.ry > 1 ||
    ![clip.cx, clip.cy, clip.rx, clip.ry].every(Number.isFinite)
  ) {
    failures.push(`mouth clip has invalid normalized bounds: ${formatClip(clip)}`);
  }
  return failures;
}

function validateOffset(label: string, offset: PortraitOffset): string[] {
  if (Math.abs(offset.dx) <= MAX_SUPPORTED_FRAME_DRIFT && Math.abs(offset.dy) <= MAX_SUPPORTED_FRAME_DRIFT) {
    return [];
  }
  return [`${label} ${formatOffset(offset)} exceeds supported ±${MAX_SUPPORTED_FRAME_DRIFT}px drift`];
}

async function calibrateAsset(asset: (typeof PORTRAIT_ASSETS)[number]): Promise<CalibratedPortrait | CalibrationFailure> {
  const file = join(process.cwd(), "public", asset.src.replace(/^\//, ""));
  const metadata = await sharp(file).metadata();
  const width = metadata.width;
  const height = metadata.height;
  const manualOverride = Boolean(PORTRAIT_MOUTH_CALIBRATION_OVERRIDES[asset.id]);
  const manualCalibration = PORTRAIT_MOUTH_CALIBRATION_OVERRIDES[asset.id];

  if (!width || !height || width / PORTRAIT_FRAME_COUNT <= 0) {
    const reason = `sheet must have ${PORTRAIT_FRAME_COUNT} equal logical frame regions; got ${width ?? "unknown"}×${height ?? "unknown"}`;
    if (manualCalibration) {
      return {
        id: asset.id,
        calibration: manualCalibration,
        talkOffset: manualCalibration.talkOffset,
        blinkOffset: { dx: 0, dy: 0 },
        mouthSignal: 0,
        source: "manual",
        note: reason,
      };
    }
    return {
      id: asset.id,
      reason,
      manualOverride,
    };
  }

  const [idle, blink, talk] = await Promise.all([
    readFrame(file, width, height, 0),
    readFrame(file, width, height, 1),
    readFrame(file, width, height, 2),
  ]);
  const registrationWindow = portraitRegistrationWindow(PORTRAIT_MEASURE_WIDTH, PORTRAIT_MEASURE_HEIGHT);
  const talkOffset = measurePortraitOffset(
    idle,
    talk,
    PORTRAIT_MEASURE_WIDTH,
    PORTRAIT_MEASURE_HEIGHT,
    16,
    registrationWindow,
  );
  // The runtime translates the talking frame by this same offset before it
  // clips the mouth. Detect against the registered frame so frame drift cannot
  // masquerade as a second mouth feature (or move the detector toward the
  // eyes, hair, or collar).
  const registeredTalk = translateRgba(talk, PORTRAIT_MEASURE_WIDTH, PORTRAIT_MEASURE_HEIGHT, talkOffset);
  const mouthSignal = maxMouthSignal(idle, registeredTalk);
  const mouthClip = detectPortraitMouthClip(
    idle,
    PORTRAIT_MEASURE_WIDTH,
    PORTRAIT_MEASURE_HEIGHT,
    registeredTalk,
  );
  const blinkOffset = resolvePortraitBlinkAlignment(idle, blink, PORTRAIT_MEASURE_WIDTH, PORTRAIT_MEASURE_HEIGHT);
  const failures = [
    ...validateClip(mouthClip, mouthSignal),
    ...validateOffset("talk offset", talkOffset),
    ...validateOffset("blink offset", blinkOffset),
  ];

  if (failures.length > 0 && !manualOverride) {
    return { id: asset.id, reason: failures.join("; "), manualOverride };
  }

  if (failures.length > 0 && manualCalibration) {
    return {
      id: asset.id,
      calibration: manualCalibration,
      talkOffset: manualCalibration.talkOffset,
      blinkOffset,
      mouthSignal,
      source: "manual",
      note: failures.join("; "),
    };
  }
  return {
    id: asset.id,
    calibration: { clip: mouthClip, talkOffset },
    talkOffset,
    blinkOffset,
    mouthSignal,
    source: "detected",
  };
}

function readExistingCalibration(): string | null {
  try {
    return readFileSync(CALIBRATION_FILE, "utf8");
  } catch (error: unknown) {
    if (error && typeof error === "object" && "code" in error && error.code === "ENOENT") return null;
    throw error;
  }
}

async function main(): Promise<void> {
  const args = new Set(process.argv.slice(2));
  const write = args.has("--write");
  const check = args.has("--check");
  const unknown = [...args].filter((arg) => arg !== "--write" && arg !== "--check");
  if (unknown.length > 0 || (write && check)) {
    throw new Error("Usage: yarn calibrate-portraits [--write | --check]");
  }

  const results: CalibratedPortrait[] = [];
  const failures: CalibrationFailure[] = [];
  for (const asset of PORTRAIT_ASSETS) {
    const result = await calibrateAsset(asset);
    if ("reason" in result) {
      failures.push(result);
      console.error(`  ${asset.id}: FAILED — ${result.reason}`);
      continue;
    }
    results.push(result);
    if (result.source === "manual") {
      console.warn(`  ${result.id}: ${result.note} (manual override retained)`);
      continue;
    }
    console.log(
      `  ${result.id}: mouth ${formatClip(result.calibration.clip)}  talk ${formatOffset(result.talkOffset)}  blink ${formatOffset(result.blinkOffset)}  signal ${result.mouthSignal.toFixed(2)}`,
    );
  }

  if (failures.length > 0) {
    console.error(`Calibration failed for ${failures.length} asset${failures.length === 1 ? "" : "s"}.`);
    if (!write && !check) return;
    process.exitCode = 1;
    return;
  }

  const generated = generatedFileText(results);
  const existing = readExistingCalibration();
  if (check) {
    if (existing !== generated) {
      console.error(`Calibration data is stale: ${relative(process.cwd(), CALIBRATION_FILE)} differs.`);
      console.error("Run yarn calibrate-portraits --write and commit the generated file.");
      process.exitCode = 1;
      return;
    }
    console.log(`Calibration data is current for ${results.length} portraits.`);
    return;
  }

  if (write) {
    if (existing === generated) {
      console.log(`Calibration data is already current for ${results.length} portraits.`);
    } else {
      writeFileSync(CALIBRATION_FILE, generated);
      console.log(`Wrote ${relative(process.cwd(), CALIBRATION_FILE)} for ${results.length} portraits.`);
    }
    return;
  }

  console.log(`Report complete for ${results.length} portraits. Use --write to update tracked calibration data.`);
}

main().catch((error: unknown) => {
  console.error(error instanceof Error ? error.message : error);
  process.exit(1);
});
