import type { MusicArrangementProfile, MusicCue } from "../types";
import {
  arrangementAffinityScore,
  assignmentRng,
  campaignMusicContexts,
  musicMissionContext,
  pickAssignedItem,
  pickBestByScore,
} from "../missionContext";

const MELODY_DEFAULT = [true, true, true, true, false, true, true, true] as const;
const PULSE_DEFAULT = [true, true, true, true, true, true, true, true] as const;
const COUNTER_DEFAULT = [false, false, false, true, false, false, true, false] as const;
const HOLD_DEFAULT = [false, false, false, false, true, false, false, false] as const;
const HAT_DEFAULT = [2, 2, 2, 2, 4, 2, 1, 2] as const;
const FILL_DEFAULT = ["tom-only", "snare-tom", "snare-tom", "snare-tom", "hat-chatter", "snare-tom", "kick-roll", "snare-tom"] as const;

export const ARRANGEMENTS: readonly MusicArrangementProfile[] = [
  {
    name: "slow-burn",
    bassStrides: [8, 8, 4, 4, 8, 4, 4, 4],
    pulseStrides: [4, 4, 2, 2, 4, 2, 2, 2],
    melodyEnabled: MELODY_DEFAULT,
    pulseEnabled: PULSE_DEFAULT,
    counterEnabled: COUNTER_DEFAULT,
    holdBass: HOLD_DEFAULT,
    hatStride: HAT_DEFAULT,
    fillStyle: FILL_DEFAULT,
    echoMelody: false,
    melodyDegreeOffset: 0,
    rhythmOffset: 0,
    drumDensity: [0.58, 0.72, 0.92, 0.88, 0.38, 0.82, 1, 0.86],
  },
  {
    name: "forward-drive",
    bassStrides: [2, 2, 2, 2, 4, 2, 2, 2],
    pulseStrides: [2, 2, 2, 2, 4, 2, 1, 2],
    melodyEnabled: MELODY_DEFAULT,
    pulseEnabled: PULSE_DEFAULT,
    counterEnabled: COUNTER_DEFAULT,
    holdBass: HOLD_DEFAULT,
    hatStride: [2, 2, 2, 2, 4, 2, 1, 2],
    fillStyle: ["snare-tom", "snare-tom", "kick-roll", "snare-tom", "hat-chatter", "snare-tom", "kick-roll", "snare-tom"],
    echoMelody: false,
    melodyDegreeOffset: 1,
    rhythmOffset: 1,
    drumDensity: [0.78, 0.94, 1, 0.96, 0.45, 1, 1, 0.95],
  },
  {
    name: "syncopated-strike",
    bassStrides: [4, 2, 2, 2, 4, 2, 2, 2],
    pulseStrides: [2, 1, 1, 2, 4, 1, 1, 1],
    melodyEnabled: MELODY_DEFAULT,
    pulseEnabled: PULSE_DEFAULT,
    counterEnabled: [false, true, false, true, false, true, true, false],
    holdBass: HOLD_DEFAULT,
    hatStride: [2, 2, 2, 2, 4, 1, 1, 2],
    fillStyle: ["hat-chatter", "snare-tom", "snare-tom", "kick-roll", "tom-only", "snare-tom", "kick-roll", "snare-tom"],
    echoMelody: false,
    melodyDegreeOffset: -1,
    rhythmOffset: 2,
    drumDensity: [0.72, 1, 0.96, 1, 0.4, 1, 1, 1],
  },
  {
    name: "ghost-signal",
    bassStrides: [8, 8, 8, 4, 8, 4, 4, 2],
    pulseStrides: [4, 4, 4, 2, 4, 2, 2, 1],
    melodyEnabled: MELODY_DEFAULT,
    pulseEnabled: [true, true, true, true, false, true, true, true],
    counterEnabled: [false, false, true, true, false, false, true, true],
    holdBass: HOLD_DEFAULT,
    hatStride: [4, 4, 2, 2, 4, 2, 1, 2],
    fillStyle: ["tom-only", "hat-chatter", "snare-tom", "hat-chatter", "hat-chatter", "tom-only", "snare-tom", "snare-tom"],
    echoMelody: false,
    melodyDegreeOffset: 2,
    rhythmOffset: 3,
    drumDensity: [0.48, 0.58, 0.72, 0.64, 0.28, 0.68, 0.88, 0.76],
  },
  {
    name: "bass-siege",
    bassStrides: [2, 2, 2, 2, 2, 2, 2, 2],
    pulseStrides: [4, 4, 2, 2, 4, 2, 2, 1],
    melodyEnabled: MELODY_DEFAULT,
    pulseEnabled: [true, false, true, true, true, true, true, true],
    counterEnabled: [false, false, false, true, false, false, true, false],
    holdBass: HOLD_DEFAULT,
    hatStride: HAT_DEFAULT,
    fillStyle: ["snare-tom", "snare-tom", "snare-tom", "snare-tom", "tom-only", "kick-roll", "kick-roll", "snare-tom"],
    echoMelody: false,
    melodyDegreeOffset: 0,
    rhythmOffset: 0,
    drumDensity: [0.72, 0.86, 0.92, 0.9, 0.46, 0.92, 1, 0.9],
  },
  {
    name: "wide-open",
    bassStrides: [8, 4, 4, 4, 8, 4, 2, 4],
    pulseStrides: [4, 2, 2, 2, 4, 2, 1, 2],
    melodyEnabled: MELODY_DEFAULT,
    pulseEnabled: PULSE_DEFAULT,
    counterEnabled: [false, true, false, true, false, false, true, false],
    holdBass: HOLD_DEFAULT,
    hatStride: [4, 2, 2, 2, 4, 2, 1, 2],
    fillStyle: FILL_DEFAULT,
    echoMelody: false,
    melodyDegreeOffset: -2,
    rhythmOffset: 1,
    drumDensity: [0.55, 0.76, 0.84, 0.78, 0.34, 0.82, 0.94, 0.8],
  },
  {
    name: "panic-run",
    bassStrides: [2, 2, 2, 2, 2, 2, 2, 2],
    pulseStrides: [2, 1, 1, 1, 2, 1, 1, 1],
    melodyEnabled: [false, true, true, true, true, true, true, true],
    pulseEnabled: PULSE_DEFAULT,
    counterEnabled: [false, true, true, true, false, true, true, true],
    holdBass: [false, false, false, false, false, false, false, false],
    hatStride: [2, 2, 2, 1, 2, 1, 1, 1],
    fillStyle: ["kick-roll", "snare-tom", "kick-roll", "snare-tom", "snare-tom", "kick-roll", "kick-roll", "snare-tom"],
    echoMelody: false,
    melodyDegreeOffset: 2,
    rhythmOffset: 2,
    drumDensity: [0.92, 1, 1, 1, 0.72, 1, 1, 1],
  },
  {
    name: "command-theme",
    bassStrides: [4, 2, 4, 2, 4, 2, 2, 2],
    pulseStrides: [2, 2, 1, 2, 4, 2, 1, 1],
    melodyEnabled: MELODY_DEFAULT,
    pulseEnabled: PULSE_DEFAULT,
    counterEnabled: COUNTER_DEFAULT,
    holdBass: HOLD_DEFAULT,
    hatStride: [2, 2, 2, 2, 4, 2, 1, 1],
    fillStyle: ["snare-tom", "snare-tom", "snare-tom", "snare-tom", "hat-chatter", "snare-tom", "kick-roll", "kick-roll"],
    echoMelody: false,
    melodyDegreeOffset: 1,
    rhythmOffset: 3,
    drumDensity: [0.68, 0.9, 0.86, 0.92, 0.38, 0.9, 1, 0.94],
  },
  {
    name: "half-time-break",
    bassStrides: [4, 2, 2, 4, 8, 4, 2, 4],
    pulseStrides: [4, 2, 2, 2, 4, 4, 1, 2],
    melodyEnabled: [false, true, true, true, false, true, true, true],
    pulseEnabled: [true, true, true, true, false, true, true, true],
    counterEnabled: [false, false, true, true, false, false, true, false],
    holdBass: [false, false, false, false, true, false, false, false],
    hatStride: [4, 2, 2, 2, 4, 4, 1, 2],
    fillStyle: ["tom-only", "snare-tom", "snare-tom", "hat-chatter", "hat-chatter", "tom-only", "kick-roll", "snare-tom"],
    echoMelody: false,
    melodyDegreeOffset: 0,
    rhythmOffset: 1,
    drumDensity: [0.5, 0.84, 0.9, 0.8, 0.22, 0.7, 1, 0.86],
  },
  {
    name: "call-and-echo",
    bassStrides: [4, 2, 2, 2, 8, 2, 2, 2],
    pulseStrides: [4, 2, 2, 2, 4, 2, 1, 2],
    melodyEnabled: [false, true, true, true, false, true, true, true],
    pulseEnabled: PULSE_DEFAULT,
    counterEnabled: [false, true, false, true, false, true, true, false],
    holdBass: HOLD_DEFAULT,
    hatStride: HAT_DEFAULT,
    fillStyle: ["hat-chatter", "snare-tom", "snare-tom", "snare-tom", "tom-only", "snare-tom", "kick-roll", "snare-tom"],
    echoMelody: true,
    melodyDegreeOffset: 1,
    rhythmOffset: 2,
    drumDensity: [0.58, 0.88, 0.94, 0.9, 0.34, 0.92, 1, 0.9],
  },
  {
    name: "double-drop",
    bassStrides: [4, 2, 2, 2, 8, 8, 2, 2],
    pulseStrides: [4, 2, 2, 2, 4, 4, 1, 2],
    melodyEnabled: [false, true, true, true, false, false, true, true],
    pulseEnabled: [true, true, true, true, true, false, true, true],
    counterEnabled: [false, false, false, true, false, false, true, true],
    holdBass: [false, false, false, false, true, true, false, false],
    hatStride: [2, 2, 2, 2, 4, 4, 1, 2],
    fillStyle: ["snare-tom", "snare-tom", "snare-tom", "hat-chatter", "hat-chatter", "tom-only", "kick-roll", "snare-tom"],
    echoMelody: false,
    melodyDegreeOffset: -1,
    rhythmOffset: 0,
    drumDensity: [0.6, 0.9, 0.94, 0.88, 0.28, 0.18, 1, 0.92],
  },
  {
    name: "anthem-lift",
    bassStrides: [4, 2, 2, 4, 8, 2, 2, 2],
    pulseStrides: [4, 2, 1, 2, 4, 2, 1, 1],
    melodyEnabled: [false, true, true, true, false, true, true, true],
    pulseEnabled: PULSE_DEFAULT,
    counterEnabled: [false, false, true, true, false, true, true, true],
    holdBass: HOLD_DEFAULT,
    hatStride: [2, 2, 2, 2, 4, 2, 1, 1],
    fillStyle: ["tom-only", "snare-tom", "snare-tom", "snare-tom", "hat-chatter", "snare-tom", "kick-roll", "kick-roll"],
    echoMelody: false,
    melodyDegreeOffset: 2,
    rhythmOffset: 1,
    drumDensity: [0.55, 0.82, 0.96, 0.88, 0.32, 0.9, 1, 0.96],
  },
  {
    name: "melody-late",
    bassStrides: [8, 4, 4, 2, 8, 2, 2, 2],
    pulseStrides: [4, 4, 2, 2, 4, 2, 1, 2],
    melodyEnabled: [false, false, true, true, false, true, true, true],
    pulseEnabled: PULSE_DEFAULT,
    counterEnabled: [false, false, false, true, false, true, true, true],
    holdBass: [true, false, false, false, true, false, false, false],
    hatStride: [4, 2, 2, 2, 4, 2, 1, 2],
    fillStyle: ["tom-only", "hat-chatter", "snare-tom", "snare-tom", "hat-chatter", "snare-tom", "kick-roll", "snare-tom"],
    echoMelody: false,
    melodyDegreeOffset: 1,
    rhythmOffset: 2,
    drumDensity: [0.5, 0.66, 0.78, 0.92, 0.3, 0.9, 1, 0.92],
  },
  {
    name: "drums-out",
    bassStrides: [8, 4, 2, 2, 8, 2, 2, 2],
    pulseStrides: [4, 2, 2, 1, 4, 2, 1, 2],
    melodyEnabled: [false, true, true, true, false, true, true, true],
    pulseEnabled: [false, true, true, true, false, true, true, true],
    counterEnabled: [false, false, true, true, false, true, true, false],
    holdBass: [true, false, false, false, true, false, false, false],
    hatStride: [4, 4, 2, 2, 4, 2, 1, 2],
    fillStyle: ["tom-only", "tom-only", "snare-tom", "kick-roll", "hat-chatter", "snare-tom", "kick-roll", "snare-tom"],
    echoMelody: false,
    melodyDegreeOffset: 0,
    rhythmOffset: 1,
    drumDensity: [0.32, 0.58, 0.88, 0.94, 0.22, 0.92, 1, 0.9],
  },
  {
    name: "inverted-hold",
    bassStrides: [8, 2, 2, 8, 4, 2, 8, 2],
    pulseStrides: [4, 2, 2, 4, 4, 2, 1, 2],
    melodyEnabled: [true, true, true, true, true, true, true, true],
    pulseEnabled: [false, true, true, true, true, true, true, true],
    counterEnabled: [true, false, true, true, false, true, false, true],
    holdBass: [true, false, false, true, false, false, true, false],
    hatStride: [4, 2, 2, 4, 2, 2, 1, 2],
    fillStyle: ["hat-chatter", "snare-tom", "kick-roll", "tom-only", "snare-tom", "snare-tom", "kick-roll", "snare-tom"],
    echoMelody: false,
    melodyDegreeOffset: -1,
    rhythmOffset: 3,
    drumDensity: [0.52, 0.88, 0.94, 0.4, 0.74, 0.92, 0.48, 0.96],
  },
  {
    name: "echo-canon",
    bassStrides: [4, 2, 2, 2, 8, 2, 2, 2],
    pulseStrides: [4, 2, 1, 2, 4, 2, 1, 2],
    melodyEnabled: [false, true, true, true, false, true, true, true],
    pulseEnabled: PULSE_DEFAULT,
    counterEnabled: [false, true, true, true, false, true, true, false],
    holdBass: HOLD_DEFAULT,
    hatStride: [2, 2, 2, 2, 4, 2, 1, 2],
    fillStyle: ["hat-chatter", "snare-tom", "snare-tom", "kick-roll", "tom-only", "snare-tom", "kick-roll", "snare-tom"],
    echoMelody: true,
    melodyDegreeOffset: 2,
    rhythmOffset: 1,
    drumDensity: [0.5, 0.86, 0.94, 0.9, 0.3, 0.92, 1, 0.9],
  },
];

export function arrangementFor(cue: MusicCue, seed: number, missionIndex: number): MusicArrangementProfile {
  const tieRng = assignmentRng(seed, cue, "music-arrangement-order");
  const ctx = musicMissionContext(seed, missionIndex);
  if (cue !== "mission" || missionIndex < 0) {
    return pickBestByScore(ARRANGEMENTS, (item) => arrangementAffinityScore(item.name, ctx), tieRng.fork(String(missionIndex)));
  }
  return pickAssignedItem(
    ARRANGEMENTS,
    campaignMusicContexts(seed),
    missionIndex,
    (item, mission) => arrangementAffinityScore(item.name, mission),
    tieRng,
    ctx,
  );
}
